name: Docker image CI build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build -t docker-alpine-php-nightly .
